trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'parallel_connection'  # Your Azure DevOps service connection name
  webAppName: 'frontendapp'                 # Your Azure Web App name
  packagePath: '$(Build.ArtifactStagingDirectory)/frontend'

steps:
# Copy static build files (already in repo) to artifact staging
- task: CopyFiles@2
  inputs:
    contents: '**/*'
    targetFolder: '$(packagePath)'
  displayName: 'Copy Static Files from Repo'

# Publish the copied files as a pipeline artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(packagePath)'
    ArtifactName: 'frontend'
  displayName: 'Publish Build Artifacts'

# Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webApp'
    appName: '$(webAppName)'
    package: '$(packagePath)'
  displayName: 'Deploy to Azure Web App'
